name: semantic_change
channels:
  - defaults
dependencies:
  - pytorch==2.5.1
  - pytorch-cuda=11.8
  - conda-forge::transformers
  - spacy
  - scipy
  - conda-forge::jupyterlab
  - ipywidgets
  - conda-forge::evaluate
  - accelerate
  - scikit-learn
  - pydantic=2.10.2
  - conda-forge::openpyxl
  - plotly
  - pot
  - conda-forge::nltk
prefix: /home/ku47/.conda/envs/semantic_change
