name: semantic_change
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - accelerate=1.1.1=pyhff2d567_0
  - aiohappyeyeballs=2.4.0=py312h06a4308_0
  - aiohttp=3.10.5=py312h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - annotated-types=0.7.0=pyhd8ed1ab_0
  - anyio=4.6.2=py312h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_0
  - arrow=1.3.0=py312h06a4308_0
  - arrow-cpp=16.1.0=hc1eb8f0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312h06a4308_0
  - attrs=24.2.0=py312h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - babel=2.11.0=py312h06a4308_0
  - beautifulsoup4=4.12.3=py312h06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli=1.0.9=h9c3ff4c_4
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.9.9=h06a4308_0
  - catalogue=2.0.10=py312h06a4308_0
  - certifi=2025.8.3=py312h06a4308_0
  - cffi=1.17.1=py312h1fdaa30_0
  - chardet=4.0.0=py312h06a4308_1003
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpathlib=0.16.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.1=py312h06a4308_0
  - confection=0.1.4=py312he106c6f_0
  - contourpy=1.3.1=py312h68727a3_0
  - cookiecutter=2.6.0=py312h06a4308_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.6=3
  - cycler=0.12.1=pyhd8ed1ab_1
  - cymem=2.0.6=py312h6a678d5_0
  - cython-blis=0.7.11=py312ha883a20_0
  - datasets=2.19.1=py312h06a4308_0
  - debugpy=1.6.7=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.8=py312h06a4308_0
  - et_xmlfile=1.1.0=py312h06a4308_1
  - evaluate=0.4.1=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h6a678d5_0
  - filelock=3.13.1=py312h06a4308_0
  - fonttools=4.56.0=py312h178313f_0
  - freetype=2.10.4=hca18f0e_2
  - frozenlist=1.5.0=py312h5eee18b_0
  - fsspec=2024.3.1=py312h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - h11=0.14.0=py312h06a4308_0
  - httpcore=1.0.2=py312h06a4308_0
  - httpx=0.27.0=py312h06a4308_0
  - huggingface_hub=0.24.6=py312h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.0=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py312h06a4308_0
  - ipython=8.27.0=py312h06a4308_0
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - jedi=0.19.1=py312h06a4308_0
  - jinja2=3.1.4=py312h06a4308_1
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - json5=0.9.25=py312h06a4308_0
  - jsonschema=4.23.0=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter-lsp=2.2.0=py312h06a4308_0
  - jupyter_client=8.6.0=py312h06a4308_0
  - jupyter_core=5.7.2=py312h06a4308_0
  - jupyter_events=0.10.0=py312h06a4308_0
  - jupyter_server=2.14.1=py312h06a4308_0
  - jupyter_server_terminals=0.4.4=py312h06a4308_1
  - jupyterlab=4.3.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312h06a4308_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - kiwisolver=1.4.8=py312h84d6215_0
  - krb5=1.20.1=h143b758_1
  - langcodes=3.3.0=pyhd8ed1ab_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcurl=8.9.1=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=hffd6297_1
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib-base=3.10.0=py312hbfdbfaf_0
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mistune=2.0.4=py312h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - mpmath=1.3.0=py312h06a4308_0
  - multidict=6.1.0=py312h5eee18b_0
  - multiprocess=0.70.15=py312h06a4308_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - murmurhash=1.0.7=py312h6a678d5_0
  - narwhals=1.26.0=pyhd8ed1ab_0
  - nbclient=0.8.0=py312h06a4308_0
  - nbconvert=7.16.4=py312h06a4308_0
  - nbformat=5.10.4=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - networkx=3.3=py312h06a4308_0
  - nltk=3.9.1=pyhd8ed1ab_1
  - notebook-shim=0.2.3=py312h06a4308_0
  - numexpr=2.10.1=py312h3c60e43_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openpyxl=3.1.5=py312h710cb58_1
  - openssl=3.5.2=h26f9b46_0
  - orc=2.0.1=h2d29ad5_0
  - overrides=7.4.0=py312h06a4308_0
  - packaging=24.1=py312h06a4308_0
  - pandas=2.2.2=py312h526ad5a_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=11.1.0=py312hcea889d_0
  - pip=24.2=py312h06a4308_0
  - platformdirs=3.10.0=py312h06a4308_0
  - plotly=6.0.0=pyhd8ed1ab_0
  - pot=0.9.5=py312hf9745cd_0
  - preshed=3.0.6=py312h6a678d5_0
  - prometheus_client=0.14.1=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=16.1.0=py312h526ad5a_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.10.2=pyh3cfb1c2_0
  - pydantic-core=2.27.1=py312h12e396e_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-fastjsonschema=2.16.2=py312h06a4308_0
  - python-json-logger=2.0.7=py312h06a4308_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py312h5eee18b_1
  - python_abi=3.12=5_cp312
  - pytorch=2.5.1=py3.12_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - pyzmq=25.1.2=py312h6a678d5_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py312h06a4308_0
  - regex=2024.9.11=py312h5eee18b_0
  - requests=2.32.3=py312h06a4308_1
  - responses=0.13.3=pyhd3eb1b0_0
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rich=13.9.4=pyhd8ed1ab_0
  - rpds-py=0.10.6=py312hb02cf49_0
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.4.5=py312hb7cc22b_0
  - scikit-learn=1.5.1=py312h526ad5a_0
  - scipy=1.13.1=py312hc5e2394_0
  - send2trash=1.8.2=py312h06a4308_0
  - setuptools=75.1.0=py312h06a4308_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=6.4.0=pyhd8ed1ab_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py312h06a4308_0
  - soupsieve=2.5=py312h06a4308_0
  - spacy=3.7.2=py312h6db74b5_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.5=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - srsly=2.4.8=py312h6a678d5_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.13.2=py312h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.17.1=py312h06a4308_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - thinc=8.2.2=py312h6db74b5_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinycss2=1.2.1=py312h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.20.1=py312h28f53f8_0
  - tomli=2.0.1=py312h06a4308_1
  - torchtriton=3.1.0=py312
  - tornado=6.4.1=py312h5eee18b_0
  - tqdm=4.66.5=py312he106c6f_0
  - traitlets=5.14.3=py312h06a4308_0
  - transformers=4.46.2=pyhd8ed1ab_0
  - typer=0.9.4=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - unidecode=1.3.8=py312h06a4308_0
  - urllib3=2.2.3=py312h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wasabi=0.10.1=pyhd8ed1ab_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - weasel=0.3.4=pyhd8ed1ab_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=1.8.0=py312h06a4308_0
  - wheel=0.44.0=py312h06a4308_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.11.0=py312h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - choreographer==1.1.1
      - en-core-web-sm==3.7.1
      - es-core-news-sm==3.7.0
      - iniconfig==2.1.0
      - kaleido==1.1.0
      - logistro==1.1.0
      - orjson==3.11.3
      - pluggy==1.6.0
      - pytest==8.4.2
      - pytest-timeout==2.4.0
      - simplejson==3.20.1
      - xlsxwriter==3.2.2
prefix: /home/ku47/.conda/envs/semantic_change
